
name: Python Build
run-name: ${{ github.actor }} is running python 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: "setup python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Run python script
        run: python my_script.py
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
